#!/bin/sh
set -ex

cd $(dirname $0)/..

export PATCH="dirtycow"

cat service.yml | envsubst > dist/dirtycow.yml
cat Dockerfile.service | envsubst > dist/Dockerfile
cp loadkpatch dist/

cp /usr/local/sbin/kpatch dist
cp /source/kpatch/kmod/core/kpatch.ko dist

# and then run docker build
